### ISSUE TITLE
gevent/telnetsrv error

### ISSUE THREAD

**Issue by jullrich** [CymmetriaResearch/MTPot#4]
getting this error after a connection/login is received

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/telnetsrvlib.py", line 821, in inputcooker
    c2 = self._inputcooker_getc(block=False)
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/telnetsrvlib.py", line 774, in _inputcooker_getc
    if not self.inputcooker_socket_ready():
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/green.py", line 44, in inputcooker_socket_ready
    return gevent.select.select([self.sock.fileno()], [], [], 0) != ([], [], [])
AttributeError: 'module' object has no attribute 'select'
<Greenlet at 0x76600080: <bound method MyTelnetHandler.inputcooker of <__main__.MyTelnetHandler instance at 0x765f5e68>>> failed with AttributeError

**Comment by itamarsher** [comment]
@jullrich This issue is caused because of some bug in telnetsrv/gevent. Please see updated readme file for possible fix/hack.

**Comment by jullrich** [comment]
after applying the fix to green.py, I am getting this error:

2016-11-16 16:42:08,497 [HoneyTelnet] INFO MTPot.py:105 [212.24.98.53:59052] logon credentials used: user:root pass:root
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/telnetsrvlib.py", line 815, in inputcooker
    c = self._inputcooker_getc()
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/telnetsrvlib.py", line 776, in _inputcooker_getc
    ret = self.sock.recv(20)
  File "/usr/lib/python2.7/dist-packages/gevent/socket.py", line 385, in recv
    return sock.recv(*args)
error: [Errno 104] Connection reset by peer
<Greenlet at 0x76602b70: <bound method MyTelnetHandler.inputcooker of <__main__.MyTelnetHandler instance at 0x765503f0>>> failed with error
